from enum import StrEnum


class LawyerVerificationStatus(StrEnum):
    PENDING = "pending"
    APPROVED = "approved"
    REJECTED = "rejected"


MAX_JOB_POSITION_LENGTH = 255
MAX_DISPLAY_NAME_LENGTH = 150
MAX_PHONE_NUMBER_LENGTH = 20
MAX_WEBSITE_LENGTH = 255
MAX_OFFICE_ADDRESS_LENGTH = 255
MAX_EDUCATION_LENGTH = 1000
MAX_LANGUAGE_LENGTH = 50
MAX_REVOCATION_REASON_LENGTH = 500