"""Add lawyer profile

Revision ID: 17f2a2ad0bd7
Revises: 701bde68d007
Create Date: 2025-10-18 20:14:52.635498

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17f2a2ad0bd7'
down_revision: Union[str, Sequence[str], None] = '701bde68d007'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lawyer_profile',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('office_address', sa.String(length=255), nullable=True),
    sa.Column('speaking_languages', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('education', sa.String(length=1000), nullable=True),
    sa.Column('current_level', sa.String(length=255), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('lawyer_profile_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lawyer_profile_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('lawyer_profile_user_id_key'))
    )
    op.create_index(op.f('lawyer_profile_id_idx'), 'lawyer_profile', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('lawyer_profile_id_idx'), table_name='lawyer_profile')
    op.drop_table('lawyer_profile')
    # ### end Alembic commands ###
