"""Update lawyer_verification

Revision ID: 701bde68d007
Revises: a277ec65b7b1
Create Date: 2025-10-16 19:32:20.566324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '701bde68d007'
down_revision: Union[str, Sequence[str], None] = 'a277ec65b7b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lawyer_verification_request',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('identity_card_front_url', sa.String(length=255), nullable=False),
    sa.Column('identity_card_back_url', sa.String(length=255), nullable=False),
    sa.Column('portrait_url', sa.String(length=255), nullable=False),
    sa.Column('law_certificate_url', sa.String(length=255), nullable=False),
    sa.Column('bachelor_degree_url', sa.String(length=255), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('current_job_position', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['user.id'], name=op.f('lawyer_verification_request_reviewed_by_admin_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('lawyer_verification_request_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lawyer_verification_request_pkey'))
    )
    op.create_index(op.f('lawyer_verification_request_id_idx'), 'lawyer_verification_request', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('lawyer_verification_request_id_idx'), table_name='lawyer_verification_request')
    op.drop_table('lawyer_verification_request')
    # ### end Alembic commands ###
