"""initial

Revision ID: ba538a0596a9
Revises: 
Create Date: 2025-10-29 14:43:10.506563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ba538a0596a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_conversations_pkey'))
    )
    op.create_index(op.f('chat_conversations_id_idx'), 'chat_conversations', ['id'], unique=False)
    op.create_table('user',
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verification_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('avatar_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('phone_number', name=op.f('user_phone_number_key'))
    )
    op.create_index(op.f('user_email_idx'), 'user', ['email'], unique=True)
    op.create_index(op.f('user_id_idx'), 'user', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_key', sa.String(length=512), nullable=True),
    sa.Column('attachment_content_type', sa.String(length=100), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], name=op.f('chat_messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('chat_messages_sender_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_index(op.f('chat_messages_conversation_id_idx'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('chat_messages_id_idx'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('chat_messages_sender_id_idx'), 'chat_messages', ['sender_id'], unique=False)
    op.create_table('chat_participants',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], name=op.f('chat_participants_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('chat_participants_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_participants_pkey')),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_chat_participant_membership')
    )
    op.create_index(op.f('chat_participants_conversation_id_idx'), 'chat_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('chat_participants_id_idx'), 'chat_participants', ['id'], unique=False)
    op.create_index(op.f('chat_participants_user_id_idx'), 'chat_participants', ['user_id'], unique=False)
    op.create_table('law_documentation',
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('s3_key', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['user.id'], name=op.f('law_documentation_uploaded_by_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('law_documentation_pkey')),
    sa.UniqueConstraint('s3_key', name=op.f('law_documentation_s3_key_key'))
    )
    op.create_index(op.f('law_documentation_id_idx'), 'law_documentation', ['id'], unique=False)
    op.create_table('lawyer_profile',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('website_url', sa.String(length=255), nullable=True),
    sa.Column('office_address', sa.String(length=255), nullable=True),
    sa.Column('speaking_languages', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('education', sa.String(length=1000), nullable=True),
    sa.Column('current_level', sa.String(length=255), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('lawyer_profile_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lawyer_profile_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('lawyer_profile_user_id_key'))
    )
    op.create_index(op.f('lawyer_profile_id_idx'), 'lawyer_profile', ['id'], unique=False)
    op.create_table('lawyer_role_revocation',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('revoked_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['revoked_by_admin_id'], ['user.id'], name=op.f('lawyer_role_revocation_revoked_by_admin_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('lawyer_role_revocation_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lawyer_role_revocation_pkey'))
    )
    op.create_index(op.f('lawyer_role_revocation_id_idx'), 'lawyer_role_revocation', ['id'], unique=False)
    op.create_table('lawyer_schedule_slot',
    sa.Column('lawyer_id', sa.Uuid(), nullable=False),
    sa.Column('start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('end_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('is_booked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lawyer_id'], ['user.id'], name=op.f('lawyer_schedule_slot_lawyer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lawyer_schedule_slot_pkey'))
    )
    op.create_index(op.f('lawyer_schedule_slot_id_idx'), 'lawyer_schedule_slot', ['id'], unique=False)
    op.create_table('lawyer_verification_request',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('identity_card_front_url', sa.String(length=255), nullable=False),
    sa.Column('identity_card_back_url', sa.String(length=255), nullable=False),
    sa.Column('portrait_url', sa.String(length=255), nullable=False),
    sa.Column('law_certificate_url', sa.String(length=255), nullable=False),
    sa.Column('bachelor_degree_url', sa.String(length=255), nullable=False),
    sa.Column('years_of_experience', sa.Integer(), nullable=False),
    sa.Column('current_job_position', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rejection_reason', sa.String(length=500), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['user.id'], name=op.f('lawyer_verification_request_reviewed_by_admin_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('lawyer_verification_request_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lawyer_verification_request_pkey'))
    )
    op.create_index(op.f('lawyer_verification_request_id_idx'), 'lawyer_verification_request', ['id'], unique=False)
    op.create_table('booking_request',
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('lawyer_id', sa.Uuid(), nullable=False),
    sa.Column('schedule_slot_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('short_description', sa.String(length=1000), nullable=False),
    sa.Column('desired_start_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('desired_end_time', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('attachment_key', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('decision_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], name=op.f('booking_request_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lawyer_id'], ['user.id'], name=op.f('booking_request_lawyer_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_slot_id'], ['lawyer_schedule_slot.id'], name=op.f('booking_request_schedule_slot_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('booking_request_pkey'))
    )
    op.create_index(op.f('booking_request_id_idx'), 'booking_request', ['id'], unique=False)
    op.create_table('chat_message_receipts',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('chat_message_receipts_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('chat_message_receipts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_message_receipts_pkey')),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_chat_message_receipt')
    )
    op.create_index(op.f('chat_message_receipts_id_idx'), 'chat_message_receipts', ['id'], unique=False)
    op.create_index(op.f('chat_message_receipts_message_id_idx'), 'chat_message_receipts', ['message_id'], unique=False)
    op.create_index(op.f('chat_message_receipts_user_id_idx'), 'chat_message_receipts', ['user_id'], unique=False)
    op.create_table('case_history',
    sa.Column('booking_request_id', sa.Uuid(), nullable=True),
    sa.Column('lawyer_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.Column('attachment_keys', postgresql.ARRAY(sa.String(length=255)), nullable=False),
    sa.Column('lawyer_note', sa.String(length=2000), nullable=True),
    sa.Column('client_note', sa.String(length=2000), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('ending_time', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['booking_request_id'], ['booking_request.id'], name=op.f('case_history_booking_request_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], name=op.f('case_history_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lawyer_id'], ['user.id'], name=op.f('case_history_lawyer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('case_history_pkey'))
    )
    op.create_index(op.f('case_history_id_idx'), 'case_history', ['id'], unique=False)
    op.create_table('lawyer_rating',
    sa.Column('case_history_id', sa.Uuid(), nullable=False),
    sa.Column('lawyer_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_history_id'], ['case_history.id'], name=op.f('lawyer_rating_case_history_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['client_id'], ['user.id'], name=op.f('lawyer_rating_client_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lawyer_id'], ['user.id'], name=op.f('lawyer_rating_lawyer_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lawyer_rating_pkey')),
    sa.UniqueConstraint('case_history_id', name=op.f('lawyer_rating_case_history_id_key'))
    )
    op.create_index(op.f('lawyer_rating_id_idx'), 'lawyer_rating', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('lawyer_rating_id_idx'), table_name='lawyer_rating')
    op.drop_table('lawyer_rating')
    op.drop_index(op.f('case_history_id_idx'), table_name='case_history')
    op.drop_table('case_history')
    op.drop_index(op.f('chat_message_receipts_user_id_idx'), table_name='chat_message_receipts')
    op.drop_index(op.f('chat_message_receipts_message_id_idx'), table_name='chat_message_receipts')
    op.drop_index(op.f('chat_message_receipts_id_idx'), table_name='chat_message_receipts')
    op.drop_table('chat_message_receipts')
    op.drop_index(op.f('booking_request_id_idx'), table_name='booking_request')
    op.drop_table('booking_request')
    op.drop_index(op.f('lawyer_verification_request_id_idx'), table_name='lawyer_verification_request')
    op.drop_table('lawyer_verification_request')
    op.drop_index(op.f('lawyer_schedule_slot_id_idx'), table_name='lawyer_schedule_slot')
    op.drop_table('lawyer_schedule_slot')
    op.drop_index(op.f('lawyer_role_revocation_id_idx'), table_name='lawyer_role_revocation')
    op.drop_table('lawyer_role_revocation')
    op.drop_index(op.f('lawyer_profile_id_idx'), table_name='lawyer_profile')
    op.drop_table('lawyer_profile')
    op.drop_index(op.f('law_documentation_id_idx'), table_name='law_documentation')
    op.drop_table('law_documentation')
    op.drop_index(op.f('chat_participants_user_id_idx'), table_name='chat_participants')
    op.drop_index(op.f('chat_participants_id_idx'), table_name='chat_participants')
    op.drop_index(op.f('chat_participants_conversation_id_idx'), table_name='chat_participants')
    op.drop_table('chat_participants')
    op.drop_index(op.f('chat_messages_sender_id_idx'), table_name='chat_messages')
    op.drop_index(op.f('chat_messages_id_idx'), table_name='chat_messages')
    op.drop_index(op.f('chat_messages_conversation_id_idx'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('user_id_idx'), table_name='user')
    op.drop_index(op.f('user_email_idx'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('chat_conversations_id_idx'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
