"""Chat + Chatbot

Revision ID: e03ab3d7c84d
Revises: 17f2a2ad0bd7
Create Date: 2025-10-19 12:42:13.324493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e03ab3d7c84d'
down_revision: Union[str, Sequence[str], None] = '17f2a2ad0bd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversations',
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_conversations_pkey'))
    )
    op.create_index(op.f('chat_conversations_id_idx'), 'chat_conversations', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('sender_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('attachment_name', sa.String(length=255), nullable=True),
    sa.Column('attachment_key', sa.String(length=512), nullable=True),
    sa.Column('attachment_content_type', sa.String(length=100), nullable=True),
    sa.Column('attachment_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], name=op.f('chat_messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], name=op.f('chat_messages_sender_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_messages_pkey'))
    )
    op.create_index(op.f('chat_messages_conversation_id_idx'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('chat_messages_id_idx'), 'chat_messages', ['id'], unique=False)
    op.create_index(op.f('chat_messages_sender_id_idx'), 'chat_messages', ['sender_id'], unique=False)
    op.create_table('chat_participants',
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], name=op.f('chat_participants_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('chat_participants_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_participants_pkey')),
    sa.UniqueConstraint('conversation_id', 'user_id', name='uq_chat_participant_membership')
    )
    op.create_index(op.f('chat_participants_conversation_id_idx'), 'chat_participants', ['conversation_id'], unique=False)
    op.create_index(op.f('chat_participants_id_idx'), 'chat_participants', ['id'], unique=False)
    op.create_index(op.f('chat_participants_user_id_idx'), 'chat_participants', ['user_id'], unique=False)
    op.create_table('lawyer_role_revocation',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('revoked_by_admin_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['revoked_by_admin_id'], ['user.id'], name=op.f('lawyer_role_revocation_revoked_by_admin_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('lawyer_role_revocation_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('lawyer_role_revocation_pkey'))
    )
    op.create_index(op.f('lawyer_role_revocation_id_idx'), 'lawyer_role_revocation', ['id'], unique=False)
    op.create_table('chat_message_receipts',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('create_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_messages.id'], name=op.f('chat_message_receipts_message_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('chat_message_receipts_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_message_receipts_pkey')),
    sa.UniqueConstraint('message_id', 'user_id', name='uq_chat_message_receipt')
    )
    op.create_index(op.f('chat_message_receipts_id_idx'), 'chat_message_receipts', ['id'], unique=False)
    op.create_index(op.f('chat_message_receipts_message_id_idx'), 'chat_message_receipts', ['message_id'], unique=False)
    op.create_index(op.f('chat_message_receipts_user_id_idx'), 'chat_message_receipts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('chat_message_receipts_user_id_idx'), table_name='chat_message_receipts')
    op.drop_index(op.f('chat_message_receipts_message_id_idx'), table_name='chat_message_receipts')
    op.drop_index(op.f('chat_message_receipts_id_idx'), table_name='chat_message_receipts')
    op.drop_table('chat_message_receipts')
    op.drop_index(op.f('lawyer_role_revocation_id_idx'), table_name='lawyer_role_revocation')
    op.drop_table('lawyer_role_revocation')
    op.drop_index(op.f('chat_participants_user_id_idx'), table_name='chat_participants')
    op.drop_index(op.f('chat_participants_id_idx'), table_name='chat_participants')
    op.drop_index(op.f('chat_participants_conversation_id_idx'), table_name='chat_participants')
    op.drop_table('chat_participants')
    op.drop_index(op.f('chat_messages_sender_id_idx'), table_name='chat_messages')
    op.drop_index(op.f('chat_messages_id_idx'), table_name='chat_messages')
    op.drop_index(op.f('chat_messages_conversation_id_idx'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('chat_conversations_id_idx'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    # ### end Alembic commands ###
