import { paletteLight } from "./paletteLight";

export const colors = {
  palette: paletteLight,
  transparent: "rgba(0, 0, 0, 0)",
  buttonDisabled: "rgba(27, 27, 34, 0.1)",
  buttonTextDisabled: "rgba(27, 27, 34, 0.38)",
  indicator: "#4a9eff",
  processStatus: {
    approved: {
      badgeColor: "#D1FAE5",
      textColor: "#059669",
    },
    pending: {
      badgeColor: "#FEF3C7",
      textColor: "#D97706",
    },
    rejected: {
      badgeColor: "#FEE2E2",
      textColor: "#DC2626",
    },
    new: {
      badgeColor: "#E0E7FF",
      textColor: "#4F46E5",
    },
    undefined: {
      badgeColor: "#F3F4F6",
      textColor: "#6B7280",
    },
  },

  primary: "#3C3EB7",
  surfaceTint: "#4C4FC8",
  onPrimary: "#FFFFFF",
  primaryContainer: "#5558D1",
  onPrimaryContainer: "#E5E4FF",
  secondary: "#595A89",
  onSecondary: "#FFFFFF",
  secondaryContainer: "#C7C7FD",
  onSecondaryContainer: "#505280",
  tertiary: "#832483",
  onTertiary: "#FFFFFF",
  tertiaryContainer: "#A03F9D",
  onTertiaryContainer: "#FFDCF6",
  error: "#BA1A1A",
  onError: "#FFFFFF",
  errorContainer: "#FFDAD6",
  onErrorContainer: "#93000A",
  background: "#FCF8FF",
  onBackground: "#1B1B22",
  surface: "#FCF8FF",
  onSurface: "#1B1B22",
  surfaceVariant: "#E3E0F2",
  onSurfaceVariant: "#464553",
  outline: "#767685",
  outlineVariant: "#C7C5D6",
  shadow: "#000000",
  scrim: "#000000",
  inverseSurface: "#303038",
  inverseOnSurface: "#F2EFFA",
  inversePrimary: "#C0C1FF",
  primaryFixed: "#E1E0FF",
  onPrimaryFixed: "#06006C",
  primaryFixedDim: "#C0C1FF",
  onPrimaryFixedVariant: "#3334AF",
  secondaryFixed: "#E1E0FF",
  onSecondaryFixed: "#151642",
  secondaryFixedDim: "#C1C2F8",
  onSecondaryFixedVariant: "#414270",
  tertiaryFixed: "#FFD7F6",
  onTertiaryFixed: "#380039",
  tertiaryFixedDim: "#FFAAF5",
  onTertiaryFixedVariant: "#7A197A",
  surfaceDim: "#DBD8E3",
  surfaceBright: "#FCF8FF",
  surfaceContainerLowest: "#FFFFFF",
  surfaceContainerLow: "#F5F2FD",
  surfaceContainer: "#EFECF7",
  surfaceContainerHigh: "#EAE7F1",
  surfaceContainerHighest: "#E4E1EC",
} as const;
